-- AlterTable
ALTER TABLE "StoreSettings" ADD COLUMN     "freeDeliveryRadiusKm" DOUBLE PRECISION NOT NULL DEFAULT 3,
ADD COLUMN     "storeLatitude" DOUBLE PRECISION NOT NULL DEFAULT 16.0334794,
ADD COLUMN     "storeLongitude" DOUBLE PRECISION NOT NULL DEFAULT 100.3798431;
